#!/bin/bash
#
# Script for testing the correct results of parallel Hitmap and reference applications
#
# (c) 2015 Arturo Gonzalez-Escribano
#

# 1. EXPERIMENT INFORMATION
# 1.1. APP NAME AND DEFAULT EXECUTABLES LIST
APP_NAME="basic_stencils"
ROOT_DIR="../.."
EXE_NAMES="$ROOT_DIR/build/examples/basic_stencils"
DEVICE_FILE_PATH="$ROOT_DIR/extern/controllers/examples/Device_Selection_Files/dev_epsilod_exp"
FPGA_KERNELS_PATH="$ROOT_DIR/examples/basic_stencils/fpga_kernels/float/"

# 1.2. APP/EXPERIMENT SPECIFIC PARAMETERS
PROCS="1 4"
SIZES="32"
ITERATIONS="1 100"
STENCILS="1dc2 1dnc4 2d4 2d8 2dnc8 2df5 3d27 4d8"

# 1.3. DIRECTORY WITH THE FILES CONTAINING THE EXPECTED RESULTS
RESULT_DIR=CorrectResults

# 1.4. NAME OF THE RESULTS FILE GENERATED BY THE EXECUTABLES
RESULT_FILE="Matrix.out.txt"

# 1.5. MPI RUN COMMAND
if [ -z "$MPI_RUN" ]; then
	MPI_RUN="srun -K --mpi=pmi2 -w gorgon -Q --exclusive -t 3 --cpus-per-task=8"
fi

# 2. WRITE HEADER
echo
echo TESTING SCRIPT
echo --------------
echo "APPLICATION: $APP_NAME"

# 3.1. TEST SPECIFIC EXECUTABLES INSTEAD OF THE PREDEFINED LIST
if [ $# -gt 0 ] && [ $1 != all ]; then
	EXE_NAMES=$@
fi
echo "EXECUTABLES: $EXE_NAMES"
echo

# 3.2. CHECK THAT EXECUTABLES HAVE BEEN GENERATED
for name in $EXE_NAMES; do
	OK=y
	if [ ! -x $name ]; then
		echo "Error: Executable not found -- $name"
		OK=n
	fi
done
if [ $OK != y ]; then
	echo
	echo -e "\tBefore using this script generate the executables"
	echo
	exit 1
fi

# 4. TESTING EXPERIMENT
function doTest() {
	echo -e "\e[1mTest $5 $2 $3 $4:\e[0m"

	# EXECUTE PROGRAM
	rm -f $RESULT_FILE
	dims=$(echo $5 | cut -c1)
	for dim in $(seq 1 $dims); do
		if [ "$dim" = "1" ]; then
			partition="EPSILOD_PARTITION=w0 EPSILOD_ALB_HEUR=NextALB"
		else
			partition="EPSILOD_PARTITION=r$dim"
		fi

		export $partition
		if [ $dims == "1" ]; then
			$MPI_RUN -n $2 ./$1 $5 $3 $4 $DEVICE_FILE_PATH --fpga-kernels-path=$FPGA_KERNELS_PATH >/dev/null 2>check.err
			echo -e "\t$partition $MPI_RUN -n $2 ./$1 $5 $3 $4 $DEVICE_FILE_PATH --fpga-kernels-path=$FPGA_KERNELS_PATH 2>check.err"
		elif [ $dims == "2" ]; then
			$MPI_RUN -n $2 ./$1 $5 $3 $3 $4 $DEVICE_FILE_PATH --fpga-kernels-path=$FPGA_KERNELS_PATH >/dev/null 2>check.err
			echo -e "\t$partition $MPI_RUN -n $2 ./$1 $5 $3 $3 $4 $DEVICE_FILE_PATH --fpga-kernels-path=$FPGA_KERNELS_PATH 2>check.err"
		elif [ $dims == "3" ]; then
			$MPI_RUN -n $2 ./$1 $5 $3 $3 $3 $4 $DEVICE_FILE_PATH --fpga-kernels-path=$FPGA_KERNELS_PATH >/dev/null 2>check.err
			echo -e "\t$partition $MPI_RUN -n $2 ./$1 $5 $3 $3 $3 $4 $DEVICE_FILE_PATH --fpga-kernels-path=$FPGA_KERNELS_PATH 2>check.err"
		elif [ $dims == "4" ]; then
			$MPI_RUN -n $2 ./$1 $5 $3 $3 $3 $3 $4 $DEVICE_FILE_PATH --fpga-kernels-path=$FPGA_KERNELS_PATH >/dev/null 2>check.err
			echo -e "\t$partition $MPI_RUN -n $2 ./$1 $5 $3 $3 $3 $3 $4 $DEVICE_FILE_PATH --fpga-kernels-path=$FPGA_KERNELS_PATH 2>check.err"
		fi

		# EXECUTION ERRORS, SKIP TESTING RESULT FILE
		if [ 0 != $? ]; then
			echo ERROR EXECUTING: $(cat check.err)
			continue
		fi

		# NOTE @segioalo workaround nfs system in trasgo cluster not detecting the file immediately
		ls &>/dev/null

		# IF THE RESULTS FILE HAS NOT BEEN GENERATED
		if [ ! -r $RESULT_FILE ]; then
			echo "Error: The executable \"$exe\" does no generate an ouput file. Try cleaning and recompiling"
			echo
			exit -1
		# CHECK THE CONTENTS OF THE RESULTS FILE
		else
			CHECK=""
			diff $RESULT_FILE $RESULT_DIR/Result.$5.$3.$4 >/dev/null || CHECK=Result
			if [ "$CHECK" != "" ]; then
				echo -e "\e[31mERROR\e[0m: $CHECK"
			else
				echo -e "\e[32mOK\e[0m"
			fi
		fi
	done
}

# EXTRA. UNCOMPRESS TEST RESULTS
tar Jxf CorrectResults.tar.xz

# SETUP ENV VARIABLES
export HIT_FILE_HEADER=no
export HIT_FILE_TEXT=yes
export TEST_EPSILOD_WRITE_OUTPUT=array
export HIT_FILE_TXT_SIZE=42
export HIT_FILE_TXT_DECIMALS=40
export OMP_NUM_THREADS=24

# 5. LOOPS FOR TESTS
for exe in $EXE_NAMES; do
	echo
	echo "Testing: $exe"
	echo "------------------------"
	for size in $SIZES; do
		for procs in $PROCS; do
			for iter in $ITERATIONS; do
				for stencil in $STENCILS; do
					doTest $exe $procs $size $iter $stencil
				done
			done
		done
	done
done

# 6. CLEAN
rm -f $RESULT_FILE
rm -f check.err
rm -rf CorrectResults
