#!/bin/bash
#
# Script for testing the correct results of epsilod and for getting its time measures. Adapted from script by Arturo Gonzalez Escribano.
#
# (c) 2024 Tomás de la Cal Esteban
#

# 1. EXPERIMENT INFORMATION
# 1.1. APP NAME AND DEFAULT EXECUTABLES LIST
APP_NAME="ALB Testing for basic_stencils"
ROOT_DIR="../.."
EXE_NAMES="$ROOT_DIR/build/examples/basic_stencils"
DEVICE_FILE_PATH="./devicefiles/"

# 1.2. APP/EXPERIMENT SPECIFIC PARAMETERS
TIMEOUT=2
CPUS_PER_TASK=24
MACHINES=("manticore")
DEVICE_FILES=("allCPUs.conf" "allCuda.conf")
PROCS=(2)
ITERATIONS=(1000)
SIZES1D=("100")
SIZES2D=("100 100")
SIZES3D=("100 100 100")
STENCILS1D=("1dc2")
STENCILS2D=("2d4")
STENCILS3D=("3d27")

# 1.3. DIRECTORY WITH THE FILES CONTAINING THE EXPECTED RESULTS
RESULT_DIR=CorrectResults

# 1.4. NAME OF THE RESULTS FILE GENERATED BY THE EXECUTABLES
RESULT_FILE="Matrix.out.txt"

# 1.5 NAME OF THE DIRECTORY WITH THE MEASURES
OUTPUT_DIR=ResultsExp

# 2. WRITE HEADER
echo
echo TESTING SCRIPT
echo --------------
echo "APPLICATION: $APP_NAME"

# 3. CHECK PARAMETERS
# 3.1. HELP
#if [ $# -lt 1 ]
#then
#	echo
#	echo -e "\tUsage: $0 [all | <executable_names>]"
#	echo
#	exit 1
#fi

# 3.2. TEST SPECIFIC EXECUTABLES INSTEAD OF THE PREDEFINED LIST
if [ $# -gt 0 ] && [ $1 != all ]; then
	EXE_NAMES=$@
fi
echo "EXECUTABLES: $EXE_NAMES"
echo

# 3.3. CHECK THAT EXECUTABLES HAVE BEEN GENERATED
for name in $EXE_NAMES; do
	OK=y
	if [ ! -x $name ]; then
		echo "Error: Executable not found -- $name"
		OK=n
	fi
done
if [ $OK != y ]; then
	echo
	echo -e "\tBefore using this script generate the executables"
	echo
	exit 1
fi

# 4. TESTING EXPERIMENT
function doTest() {
    echo -e -n "Test $6 $4 $5 $3 $8:\t"
    
    noextensiondevicefile=$(basename "$devicefile" .conf)


    resname="$6 $4 $5 $3 $noextensiondevicefile.res"
    errname="$6 $4 $5 $3 $noextensiondevicefile.err"

    resname_nospaces=$(echo $resname | sed 's/ /_/g')
    errname_nospaces=$(echo $errname | sed 's/ /_/g')

    rm -f $RESULT_FILE

    $1 -n $3 ./$2 $6 $4 $5 $7 >./$OUTPUT_DIR/$resname_nospaces 2>./$OUTPUT_DIR/$errname_nospaces

    # EXECUTION ERRORS, SKIP TESTING RESULT FILE
	if [ 0 != $? ]; then
		echo ERROR EXECUTING: $(cat $errname_nospaces)
		continue
	fi

    # Force NFS to sync to make sure that results are present
	ls &>/dev/null

	# IF THE RESULTS FILE HAS NOT BEEN GENERATED
	if [ ! -r $RESULT_FILE ]; then
		echo "Error: The executable \"$exe\" does no generate an ouput file. Try cleaning and recompiling"
		echo
		exit -1
	# CHECK THE CONTENTS OF THE RESULTS FILE
	else
		CHECK=""
        size_nospaces=$(echo $4 | sed 's/ /./g')
		diff $RESULT_FILE $RESULT_DIR/Result.$6.$size_nospaces.$5 >/dev/null || CHECK=Result
		if [ "$CHECK" != "" ]; then
			echo ERROR: $CHECK
		else
			echo OK
		fi
	fi
}



# SETUP ENV VARIABLES
export HIT_FILE_HEADER=no
export HIT_FILE_TEXT=yes
export TEST_EPSILOD_WRITE_OUTPUT=array
export HIT_FILE_TXT_SIZE=42
export HIT_FILE_TXT_DECIMALS=40
export OMP_NUM_THREADS=24

# SETUP RESULTS DIR

mkdir $OUTPUT_DIR


# 5. LOOPS FOR TESTS
for exe in $EXE_NAMES; do
	echo
	echo "Testing: $exe"
	echo "------------------------"
    for machine in "${MACHINES[@]}"; do
        command="srun -w $machine --mpi=pmi2 --cpus-per-task=$CPUS_PER_TASK -Q --exclusive -t $TIMEOUT"
        for size in "${SIZES1D[@]}"; do
            for procs in "${PROCS[@]}"; do
                for iter in "${ITERATIONS[@]}"; do
                    for stencil in "${STENCILS1D[@]}"; do
                        for conffile in "${DEVICE_FILES[@]}"; do
                            devicefile="$DEVICE_FILE_PATH$conffile"
                            doTest "$command" "$exe" "$procs" "$size" "$iter" "$stencil" "$devicefile" "$conffile"
                        done
                    done
                done
            done
        done
        for size in "${SIZES2D[@]}"; do
            for procs in "${PROCS[@]}"; do
                for iter in "${ITERATIONS[@]}"; do
                    for stencil in "${STENCILS2D[@]}"; do
                        for conffile in "${DEVICE_FILES[@]}"; do
                            devicefile="$DEVICE_FILE_PATH$conffile"
                            doTest "$command" "$exe" "$procs" "$size" "$iter" "$stencil" "$devicefile" "$conffile"
                        done
                    done
                done
            done
        done
        for size in "${SIZES3D[@]}"; do
            for procs in "${PROCS[@]}"; do
                for iter in "${ITERATIONS[@]}"; do
                    for stencil in "${STENCILS3D[@]}"; do
                        for conffile in "${DEVICE_FILES[@]}"; do
                            devicefile="$DEVICE_FILE_PATH$conffile"
                            doTest "$command" "$exe" "$procs" "$size" "$iter" "$stencil" "$devicefile" "$conffile"
                        done
                    done
                done
            done
        done
    done
done

# 6. CLEAN
rm -f $RESULT_FILE
rm -f check.err
#rm -rf CorrectResults
